/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProductSatisfactionSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSurvey"
      | "decryptionCallback"
      | "endSurvey"
      | "finalizeProduct"
      | "getDecryptedSum"
      | "getEncryptedSum"
      | "getSurvey"
      | "getSurveyCount"
      | "hasSubmitted"
      | "hasUserSubmitted"
      | "isSurveyFullyFinalized"
      | "markSurveyFullyFinalized"
      | "protocolId"
      | "submitRatings"
      | "surveys"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FinalizeRequested"
      | "RatingSubmitted"
      | "SurveyCreated"
      | "SurveyEnded"
      | "SurveyFinalized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSurvey",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "endSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProduct",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedSum",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSum",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurveyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSurveyFullyFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markSurveyFullyFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitRatings",
    values: [BigNumberish, BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "surveys",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endSurvey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSurvey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSurveyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSurveyFullyFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markSurveyFullyFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRatings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "surveys", data: BytesLike): Result;
}

export namespace FinalizeRequestedEvent {
  export type InputTuple = [surveyId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [surveyId: bigint, requestId: bigint];
  export interface OutputObject {
    surveyId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [surveyId: BigNumberish, user: AddressLike];
  export type OutputTuple = [surveyId: bigint, user: string];
  export interface OutputObject {
    surveyId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyCreatedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    title: string,
    admin: AddressLike
  ];
  export type OutputTuple = [surveyId: bigint, title: string, admin: string];
  export interface OutputObject {
    surveyId: bigint;
    title: string;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyEndedEvent {
  export type InputTuple = [surveyId: BigNumberish];
  export type OutputTuple = [surveyId: bigint];
  export interface OutputObject {
    surveyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyFinalizedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    productIndex: BigNumberish,
    decryptedSum: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    productIndex: bigint,
    decryptedSum: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    productIndex: bigint;
    decryptedSum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProductSatisfactionSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): ProductSatisfactionSurvey;
  waitForDeployment(): Promise<this>;

  interface: ProductSatisfactionSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSurvey: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _productNames: string[],
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  endSurvey: TypedContractMethod<
    [_surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeProduct: TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDecryptedSum: TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getEncryptedSum: TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [string],
    "view"
  >;

  getSurvey: TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string[],
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        productCount: bigint;
        productNames: string[];
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;

  getSurveyCount: TypedContractMethod<[], [bigint], "view">;

  hasSubmitted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasUserSubmitted: TypedContractMethod<
    [_surveyId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  isSurveyFullyFinalized: TypedContractMethod<
    [_surveyId: BigNumberish],
    [boolean],
    "view"
  >;

  markSurveyFullyFinalized: TypedContractMethod<
    [_surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitRatings: TypedContractMethod<
    [
      _surveyId: BigNumberish,
      _encryptedRatings: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  surveys: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean, string, bigint] & {
        title: string;
        description: string;
        productCount: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSurvey"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _productNames: string[],
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endSurvey"
  ): TypedContractMethod<[_surveyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeProduct"
  ): TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDecryptedSum"
  ): TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSum"
  ): TypedContractMethod<
    [_surveyId: BigNumberish, _productIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurvey"
  ): TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string[],
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        productCount: bigint;
        productNames: string[];
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurveyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserSubmitted"
  ): TypedContractMethod<
    [_surveyId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSurveyFullyFinalized"
  ): TypedContractMethod<[_surveyId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "markSurveyFullyFinalized"
  ): TypedContractMethod<[_surveyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitRatings"
  ): TypedContractMethod<
    [
      _surveyId: BigNumberish,
      _encryptedRatings: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "surveys"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean, string, bigint] & {
        title: string;
        description: string;
        productCount: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "FinalizeRequested"
  ): TypedContractEvent<
    FinalizeRequestedEvent.InputTuple,
    FinalizeRequestedEvent.OutputTuple,
    FinalizeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyCreated"
  ): TypedContractEvent<
    SurveyCreatedEvent.InputTuple,
    SurveyCreatedEvent.OutputTuple,
    SurveyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyEnded"
  ): TypedContractEvent<
    SurveyEndedEvent.InputTuple,
    SurveyEndedEvent.OutputTuple,
    SurveyEndedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyFinalized"
  ): TypedContractEvent<
    SurveyFinalizedEvent.InputTuple,
    SurveyFinalizedEvent.OutputTuple,
    SurveyFinalizedEvent.OutputObject
  >;

  filters: {
    "FinalizeRequested(uint256,uint256)": TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;
    FinalizeRequested: TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;

    "SurveyCreated(uint256,string,address)": TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
    SurveyCreated: TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;

    "SurveyEnded(uint256)": TypedContractEvent<
      SurveyEndedEvent.InputTuple,
      SurveyEndedEvent.OutputTuple,
      SurveyEndedEvent.OutputObject
    >;
    SurveyEnded: TypedContractEvent<
      SurveyEndedEvent.InputTuple,
      SurveyEndedEvent.OutputTuple,
      SurveyEndedEvent.OutputObject
    >;

    "SurveyFinalized(uint256,uint256,uint256)": TypedContractEvent<
      SurveyFinalizedEvent.InputTuple,
      SurveyFinalizedEvent.OutputTuple,
      SurveyFinalizedEvent.OutputObject
    >;
    SurveyFinalized: TypedContractEvent<
      SurveyFinalizedEvent.InputTuple,
      SurveyFinalizedEvent.OutputTuple,
      SurveyFinalizedEvent.OutputObject
    >;
  };
}
